---
title: "Identifying the True Origin of DNS Traffic Without Reference to Client Source Address"
date: "`r format(Sys.time(), format='%Y-%m-%d %H:%M:%S %z')`"
author:
  - name: Joe Abley
    affiliation:
      - Western University, London, Ontario, Canada
      - Afilias Canada, Toronto, Ontario, Canada
      - 'jabley@uwo.ca, jabley@afilias.info'
abstract: |
  We demonstrate a classifier system that is able to identify the originating
  system respobsible for stateless Domain Name System (DNS) traffic received
  at an authoritative DNS server without reference to source address. The
  ability to determine whether particular DNS query traffic received at an
  authoritative server is legitimately sourced from a particular client system
  is useful in identifying some classes of malicious traffic in production
  DNS systems.

bibliography: "IEEEabrv,./project"  
  
output:
  pdf_document:
    template: "lib/ieee-pandoc-template.tex"
    keep_tex: yes
    fig_caption: yes
    pandoc_args:
      - --filter
      - pandoc-crossref
      - --natbib
classoption: conference
link-citations: yes
reference-section-title: References
natbib: yes
documentclass: IEEEtran
# ----------- Pandoc crossref config ---------
# pandoc-crossref
eqnPrefix:
    - ''
    - ''
figPrefix:
  - "figure"
  - "figures"
tblPrefix:
  - "table"
  - "tables"
secPrefix:
  - "section"
  - "sections"
autoSectionLabels: true # prepend sec: to section titles
---

```{r setup, include=FALSE}
library(pander)
library(knitr)

Sys.setenv(RSTUDIO_PANDOC = "/Users/jabley/Library/Haskell/bin")
Sys.setenv(PATH = paste(Sys.getenv('PATH'), '/Users/jabley/Library/Haskell/bin', sep=':'))
```

# Introduction
\label{sec:introduction}

The Domain Name System (DNS) includes a wire protocol with which structured requests and responses are exchanged over a network. The DNS protocol was originally specified [@rfc1034][@rfc1035] for use over both the Transmission Control Protocol (TCP) [@rfc793] and the User Datagram Protocol (UDP) [@rfc768] and the use of other transports have also been documented [@rfc7858][@rfc8484][@huitema-quic-dnsoquic-05]. At present, however, UDP is the overwhelmingly dominant transport protocol in use; for example, according to statistics published by ICANN for queries received at the L root server, UDP accounts for 98% of all queries received\footnote{\url{http://stats.dns.icann.org/plotcache/L-Root/transport_vs_qtype/2018-12-03T00:00-2018-12-03T23:59-all.html}}.

Since UDP transport for DNS is stateless, consisting of single-datagram queries and responses with no setup or tear-down handshake, there are limited opportunities to verify the legitimacy of a source address. DNS servers are consequently frequently used as amplifiers in reflection attacks [@rfc5358]. Although some such attacks are trivially identified, e.g. by Query Type (QTYPE), many are more difficult. By choosing query parameters that match legitimate, real-world use of the DNS, attackers can make it difficult for their traffic to be identified and blocked without causing collateral damage. This is especially true of amplification attacks against DNS resolvers.

The clients of authoritative DNS servers are most usually DNS resolvers. These client systems receive requests from end-user applications (or downstream resolvers). Different client resolver systems are observed to send different mixes of DNS traffic; for example, a resolver system that mainly serves end-users will send a different mixture of queries to authoritative servers than one which serves a specific application like Internet mail [@rfc5321], which might reasonably be expected to have a much higher proportion of query traffic with \texttt{QTYPE=MX}.

Afilias Canada\footnote{\url{https://afilias.info/}} operates authoritative DNS infrastructure for around 300 top-level domains, including several that attract high levels of query traffic such as INFO and ORG. This infrastructure is distributed globally using anycast service distribution [@rfc4786], using commodity transit services, public peering and so-called Private Network Interconnects (PNIs). The real origin of queries received over a PNI can be known with high accuracy; the origin of queries received over the Internet, in contrast, cannot. We refer to the former as *trusted* paths, and the latter as *untrusted*. Trusted paths exist to Google Public DNS\footnote{\url{https://dns.google.com}}, a public DNS resolver system configured for use by a large number of end-users, and Facebook\footnote{\url{https://www.facebook.com}}, whose resolver systems are mainly used by back-end systems that build previews for links shared between users of Facebook's social media platform. The traffic patterns of each are expected to be usefully different.

While real-time anomoly detection in DNS traffic remains an elusive problem, the ability to classify traffic apparently received by particular sources as being legitimate is useful in the forensic analysis of traffic spikes since it provides the opportunity to distinguish between illegitimate, unwanted traffic and traffic from clients that just happen to be busy, e.g. due to a burst in popularity in a particular web page, or changes in the Time To Live (TTL) parameters of high-use domain names. This paper describes a system that aims to provide such a classification.

A raw DNS dataset is collected in the form of individual (request, response) DNS messages received and sent from and to a single apparent source over a time period. We extract features from those messages and count them over a short time interval to build a vector of features that describes the traffic during that time. Each such vector, once normalised, represents a single observation. Sets of observations can be collected from adjacent sample intervals. Where the traffic arrived from a trusted source, the source system can be identified and included in the dataset which can subsequently be used for training. Traffic that definitively did not arrive from a trusted source can be used to classify traffic as "other". The resulting model can be used to classify query streams from unknown sources to classify the origin of the query traffic as "Facebook", "Google" or "Other".

This paper is organised as follows. Section \ref{sec:introduction} introduces the problem and provides some high-level background on the DNS. Section \ref{sec:background} provides a short introduction to the algorithms and accuracy measures that are used to build the model. Some other work on applying machine learning techniques to problems in the DNS are described in section \ref{sec:related}. Data collection and preprocessing, feature engineering and choice of learning and validation algorithms are discussed in section \ref{sec:methodology}. Section \ref{sec:evaluation} describes the evaluation of the resulting model. Section \ref{sec:conclusion} provides a summary of the work described in this paper, and section \ref{sec:future} identifies some areas for future study.

# Background
\label{sec:background}

Two multiclass classifiers are evaluated for this model in section \ref{sec:classifiers}, below. The approach used to evaluate the accuracy of each is described in section \ref{sec:accuracy}.

## Classifier Methods
\label{sec:classifiers}

### Multiclass Support Vector Machine

The classifier used in this paper was constructed as a series of Support Vector Machines (SVM), each used as a binary classifier. SVM represents $n$-dimensional support vectors in an $n$-axis hyperspace and identifies a hyperplane boundary between observations known to be in different categories to facilitate classification of unlabelled test sets. Those boundaries can then be used to classify unlabelled observations.

Multiclass classification is achieved using $k(k-1)/2$ *one-against-one* binary classifiers combined with a max-wins voting scheme, as discussed in [@10.1007/11494683_28].

The SVM implementation used to construct this model exposes several hyperparameters that can be tuned, as well as a native grid search to assist identification of optimal parameters for a supplied validation dataset.

### Random Forest

Random Forests (RF) [@Breiman2001] combine many decision trees at training time into an ensemble learning model. RF is an improvement over the use of individual decision trees since they are far less susceptible to over-fitting; in fact, Breiman asserts that RF in the general case does not over-fit.

The RF implementation used to construct this model exposes several parameters that can be tuned, including the maximum tree depth, the maximum number of nodes and the bootstrap sample size.

## Accuracy

Short introduction to the algorithms  and the accuracy measures used. Generic only, and nothing about how the algorithms were used or the data. Half page, max one page.

# Related Work
\label{sec:related}

Machine learning techniques were applied to the problem of classifying so-called core domains as part of a threat assessment in a production system at Nominum\footnote{Nominum was acquired by Akamai in November 2017} [@Yuzifovichbotconf2017] [@YuzifovichOARC2017]. This problem has some similarities to the problem described in this paper, and illustrates the use of continuous learning to upadate an already-trained model on arrival of new data.

The .NZ registry maintains a set of business intelligence datasets which are constructed in part by analysis of  queries received at authoritative DNS servers. In order to improve the accuracy of those datasets, machine learning techniques were used to build models that could classify query sources as DNS resolvers or other systems (e.g. systems performing active monitoring of the DNS). The work included extensive feature analysis and incorporated substantial domain knowledge derived from earlier analysis. [@Qiao2018] [@QiaoOARC2018].

A study in the application of different machine learning techniques was presented in [@Sammour2017] as part of an attempt to train a model to identify Internet traffic tunnelled over the DNS protocol.

The approach described in this paper differs from other approaches described above in that it acknowledges the problems inherent in grouping DNS transactions together without the ability to be certain that the apparent sources of DNS queries are legitimate.

# Methodology
\label{sec:methodology}

## Overview
Complete sets of query data received over both trusted and untrusted paths were collected at a representative number of Afilias anycast sites, in the form of packet captures in PCAP format.\footnote{PCAP, named after the C library \texttt{libpcap}, is the file format used by the \texttt{tcpdump} utility.}

## Data Collection and Preprocessing
 * remove non-UDP traffic
 * isolate collections of queries and responses that correspond to a single trusted or untrusted source address
 * count parameters in individual queries and responses within regular sample intervals
 * normalise counts in each sample

## Feature Engineering
 
## Validation Process

Validation process (hold-out, k-fold, ...)

No results

No code

Formulas can be included as long as they are not specific to a particular programming language.

# Evaluation
\label{sec:evaluation}

Results of the process I applied

Can include a paragraph describing what languages, packages and libraries were used.

Possibilities: accuracy measures, graphs showing tuning process, tables and graphs comparing different approaches, tuned parameter ranges and selected values.

No code.

# Conclusion
\label{sec:conclusion}

Short summary of the paper/report

Should include problem description, how I solved it and the main results.

# Future Study
\label{sec:future}

 * different algorithms
 * incorporate new classes (new trusted paths to resolvers)
 * string-similarity metrics for QNAMEs
 * quantitative measurements of query entropy

# Colophon

This document has been written in R Markdown\footnote{\url{https://rmarkdown.rstudio.com}}; the code used to produce the output included in this document is consequently included with the document source\footnote{\url{https://github.com/ableyjoe/uwo-mesc/tree/master/ECE-9603A-001-GF18/project}}. The production of this document in IEEEtran style from R Markdown was informed by a pseudonomymously-attributed community project\footnote{\url{https://github.com/mathematicalcoffee/IEEEtran-rmarkdown}}.
